version: '3.9'

services:
  urlibrary-front:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: urlibrary-front
    ports:
      - '3000:3000'
    working_dir: '/app'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    init: true
